runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 0.5

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7
  target_concurrent_requests: 100
